eks/local.tf
eks/main.tf
eks/outputs.tf
eks/variables.tf
local.tf
main.tf
outputs.tf
variables.tf

This PR integrates the [thanos module](https://github.com/camptocamp/devops-stack-module-thanos) with the kube-prometheus-stack and it goes hand-in-hand with [this PR](https://github.com/camptocamp/devops-stack-module-thanos/pull/2) in the thanos module. It deploys the configuration and resources needed to deploy a Thanos sidecar with Prometheus and then export the metrics to an S3 bucket for persistence.
All these configurations are applied conditionally when a variable  `metrics_archives` is passed on module call. This also means that the kube-prometheus-stack module must depend on the thanos module in the case that we deploy the latter.
The code is mainly adapted to an AWS deployment but is easily adaptable to other deployments, the only thing that needs changing is the bucket …

feat(thanos): add needed configuration and resources to deploy Thanos

---

README.adoc
aks/README.adoc
aks/extra-variables.tf
aks/local.tf
aks/main.tf
outputs.tf

:warning: **BREAKING CHANGE**
We only need to pass the managed cluster resource group name as a module input to create "kube-prometheus-stack-prometheus" managed identity, the other resource group variable is useless.
Also, the name of the data source that we use to request the resource group information is made more explicit.
And finally, terraform fmt.

chore(azure)!: delete useless resource group variable and clean up

---

README.adoc
aks/README.adoc
aks/output.tf
eks/README.adoc

This output is present in all cloud provider modules except Azure. This output is used to manage dependencies between modules.
Tested on Azure, no further tests needed.

feat(Azure): add missing ID output

---

README.adoc
aks/README.adoc
eks/README.adoc
kind/extra-variables.tf

**Summary**
Thanos sidecar can now optionally access storage endpoint in insecure mode. Use `insecure` attribute of `metrics_storage` input.
**Test platform**

feat(kind): allow insecure access to storage endpoint

---

README.adoc
aks/README.adoc
aks/extra-variables.tf
aks/locals.tf
aks/main.tf
charts/kube-prometheus-stack/templates/azureidentity.yaml
charts/kube-prometheus-stack/templates/azureidentitybinding.yaml
eks/README.adoc
kind/README.adoc

User can now choose between key-based and identity-based access to object storage by thanos sidecar.
The variable `metrics_storage` is refactored as follow:
```hcl
metrics_storage = {
container       = azurerm_storage_container.metrics.name
storage_account = azurerm_storage_account.metrics.name
managed_identity_node_rg_name = module.cluster.node_resource_group # Unset when using account key.
storage_account_key = azurerm_storage_account.metrics.primary_access_key # Unset when using a managed identity
}
```
**Imporant:** when using identity-based access, aad-pod-identity must be declared as module dependency.

feat(azure)!: use managed identity to access object storage

---

README.adoc
aks/README.adoc
eks/README.adoc
eks/locals.tf
kind/README.adoc

Fix a terraform error that would make the plan/apply fail when var.metrics_storage is null.
NO

fix(eks): terraform error when var.metrics_storage is null

---

README.adoc
aks/README.adoc
eks/README.adoc
kind/README.adoc
locals.tf

I added a way to skip TLS validation of the OIDC authentication of Grafana when using `ca-issuer` as a Certificate Authority.

fix(grafana): ignore self-signed certificates for Grafana

---

locals.tf

Configure an additional service port for oauth-proxy on prometheus and alertmanager, instead of modifying the default port. This seems more in line with the chart's design, allows us to:
- keep "selfMonitor" enabled (ServiceMonitors built in the chart)
- get rid of the custom monitoring targets
- make the prometheus and alertmanager dashboards that come with the chart work as expected

fix: improve services / monitoring customization

---

README.adoc
aks/README.adoc
eks/README.adoc
kind/README.adoc
main.tf

This PR allows to diff rendered k8s manifests in Terraform plan upon Helm values change. "Raw" Helm values shown in the plan as ArgoCD application input are also kept for the moment.

feat: diff k8s manifests

---

.github/workflows/terraform-docs.yaml
README.adoc
aks/README.adoc
aks/locals.tf
aks/main.tf
eks/README.adoc
eks/locals.tf
eks/main.tf
kind/README.adoc
kind/extra-variables.tf
kind/locals.tf
kind/main.tf
sks/README.adoc
sks/extra-variables.tf
sks/locals.tf
sks/main.tf
sks/outputs.tf
sks/terraform.tf
sks/variables.tf

- Add support for SKS clusters and SOS bucket storage.
- Refactor the code through all variants to improve the readability and rename a few parameters in the variables (_see next section_). 
:warning: **Do a _Rebase and merge_.**

feat/fix: add SKS variant and standardize bucket configuration on other variants

---

.github/workflows/chart-update.yaml
README.adoc
charts/kube-prometheus-stack/Chart.yaml
main.tf

This PR:
- re-adds the support to deactivate the auto-sync, which was broken by the use of dynamic Terraform blocks on the PR #74. This is not a breaking change, because users can still use the old way of passing an empty map to the `app_autosync` variable in order do deactivate the auto-sync.
- adds the workflow that enables the auto-upgrade of the Helm charts.
:warning: **Do a _Rebase and merge_**

fix/ci: fix autosync deactivation and add chart auto-updater workflow

---

README.adoc
aks/README.adoc
docs/modules/ROOT/nav.adoc
eks/README.adoc
kind/README.adoc
main.tf
sks/README.adoc
variables.tf

Adds a variable to conditionally enable the output of Helm templates on the Terraform plan. I've set the value as false, as discussed and added a warning to the variable description, as discussed in our weekly.
:warning: **Please note that the first time you apply this release, it will output a monstrous Terraform plan saying a resource will be deleted as long as thousands of lines.** To avoid problems, it's best you only apply this change without any other changes at the same time.

fix: add variable to deactivate the output of Helm templates on plan

---

README.adoc
aks/README.adoc
aks/main.tf
eks/README.adoc
eks/main.tf
kind/README.adoc
kind/main.tf
locals.tf
main.tf
sks/README.adoc
sks/main.tf
variables.tf

This PR:
- Adds the required variables and configuration to allow the module to be deployed on a different cluster than Argo CD.
- Adds the possibility of placing the application inside a specified Argo CD project in order to avoid having a single project for each application throughout multiple clusters.
- Adds labels and a variable to add more labels to the Argo CD application to make it easier to sort applications on the web interface of Argo CD.
- Updates the images of OAuth2-Proxy and curl. 
**All these changes are made in preparation for having a centralized Argo CD that controls applications throughout multiple clusters.**
:warning: **Do a _Rebase and merge_.**

feat: add variables to set AppProject, labels and destination cluster

---

README.adoc
aks/README.adoc
eks/README.adoc
kind/README.adoc
main.tf
sks/README.adoc
variables.tf

This feature was controversial within the team and for that reason a variable to activate was added before. However, this feature was not propagated to the other modules, so we decided as a team to remove it altogether for consistency between modules.

fix!: remove the Helm diff

---

README.adoc
locals.tf

Use thanos frontend to ensure Query splitting and other config is applied.
:warning: Grafana pod might need a restart to apply the new config.

fix(Grafana): Thanos datasource url

---

README.adoc
aks/README.adoc
eks/README.adoc
kind/README.adoc
locals.tf
sks/README.adoc
variables.tf

Enables routes to be matched several times (opt-in). This doesn't change default behavior.
Note: the default value that was added in the `locals.tf`, the `continue: false`, will be shown in your next terraform plan.

feat(alertmanager): continue matching

---

README.adoc
aks/README.adoc
eks/README.adoc
kind/README.adoc
locals.tf
sks/README.adoc
variables.tf

This PR adds a variable to customize the dataproxy timeout, which is set to 30 seconds by default. This allows to increase the timeout if needed for example timeout awaiting response header error while querying.

feat(grafana): create a variable to set a dataproxy time

---

README.adoc
aks/README.adoc
aks/main.tf
eks/README.adoc
eks/main.tf
kind/README.adoc
kind/main.tf
locals.tf
main.tf
sks/README.adoc
sks/main.tf
variables.tf

The main changes of this PR are the following:
- **fix!: hardcode the release name to remove the destination cluster**
I found out that Argo CD passes the name of the application as a value to set the Helm chart. This means that all the templating that used `{ $.Release.Name }` would resolve to the name given to Argo CD application.
In a multicluster deployment, using a single Argo CD, the names of the applications must be different. We solved that by appending the cluster name to the default application name when deploying on different clusters than `in-cluster`. However, this resulted in multiple problems for deployments that depended on the name of the application being static, so this solves that.
This is a breaking change because sometimes this requires an application to be deleted …

fix!: change the default cluster issuer, remove the namespace variable and hardcode the Helm release name

---

README.adoc
aks/README.adoc
eks/README.adoc
kind/README.adoc
locals.tf
sks/README.adoc

This PR enables the export of metrics for the Thanos sidecar, when it is enabled. This is required and relates to the PR https://github.com/camptocamp/devops-stack-module-thanos/pull/73 on the Thanos module.

feat: enable the export of Thanos sidecar metrics

---

README.adoc
aks/README.adoc
aks/main.tf
eks/README.adoc
eks/main.tf
kind/README.adoc
kind/main.tf
locals.tf
sks/README.adoc
sks/main.tf
variables.tf

Hello,
We have a need to use URLs without the .apps. part, in order to achieve that without introducing a breaking change we propose a new variable subdomain that defaults to apps, that way we can set it to an empty string on our side.

feat: add a subdomain variable

---

README.adoc
aks/README.adoc
eks/README.adoc
kind/README.adoc
locals.tf
sks/README.adoc

The SSL redirection is no longer defined by these annotations, I think this is a leftover from ancient code. The HTTP -> HTTPS redirection is handled natively by the Traefik module and is enabled by default (a variable is available to deactivate it if necessary).

fix: remove legacy ingress annotations

---

README.adoc
aks/README.adoc
aks/main.tf
eks/README.adoc
eks/main.tf
kind/README.adoc
kind/main.tf
locals.tf
sks/README.adoc
sks/main.tf
variables.tf

This PR adds a variable to set resources' limits and requests on the module components.
Having default values is good practice to prevent that our components could eventually starve other workloads on the cluster. However, these should probably be adapted in production clusters and are only a safeguard in case someone forgets to set them.
It also upgrades the images of OAuth Proxy and curl, which are used for authenticating to the services of the kube-prometheus-stack.
:warning: **Do a _Rebase and merge_**

feat: add a variable to set resources and upgrade OAuth Proxy and curl images

---

README.adoc
aks/README.adoc
eks/README.adoc
eks/extra-variables.tf
eks/locals.tf
eks/main.tf
kind/README.adoc
sks/README.adoc

This commit solves ISDEVOPS-279 and ISDEVOPS-283 for the EKS variant. That is, it adds support for creating the IAM role automatically inside the modules while also giving the chance to provide a custom one managed by the user.
:warning: **Do a _Rebase and merge_**

feat(eks)!: add option to create IAM role for the metrics storage

---

README.adoc
locals.tf

This PR adds a runbook URL to the alert templates sent to Slack, which is useful for debugging purposes. It includes a URL that redirects to documentation detailing the alerts. We have implemented this feature in our Shelter module, and I believe it would be beneficial to include it in the kube-prometheus-stack module as well.

feat: add Runbook URL on alertmanager template

---

aks/locals.tf
locals.tf

This PR fixes an issue in AKS deployments when NOT using managed identities to configure the metrics storage. When that was the case, the value for the key `kube-prometheus-stack.prometheus` was `null` and that prevented merging the values that came from the `helm_values` variable.
We also changed the registry for the `curl` image in order to avoid the strict rate-limits from Docker Hub.

fix(aks): add merge() to avoid null value that breaks values generation

---

README.adoc
aks/README.adoc
eks/README.adoc
kind/README.adoc
locals.tf
sks/README.adoc

We don't use a cluster.name in our URLs (the platform is unique and upgraded in place)
So the ingresses were configured with two identical tls hosts, which was firing alerts about duplicate time series and so on.
I added a distinct() so that in our case we have just one host in the end and that the current stacks are not impacted.

feat: add distinct to avoid duplicates in ingreses hosts lists

---

README.adoc
aks/README.adoc
eks/README.adoc
kind/README.adoc
locals.tf
sks/README.adoc
variables.tf

Integrates a Persistent Volume Claim (PVC) to enable persistent storage for Alertmanager alerts. This ensures that alerts remain available across pod restarts and deployments, preventing loss of alert history and state.

feat: add pvc for alertmanager data
